### ISSUE TITLE
Can you share the pretrained models

### ISSUE THREAD

**Issue by meocong** [anubhav4sachan/fingerprint-recognition#1]
I am excited about your work with fingerprint fixed-length embedding, can you share the weight of pre-trained models, thank you!

**Comment by anubhav4sachan** [comment]
It is not possible to share (by me) due to privacy (& ethical) concerns.
However, you may contact my supervisor(s) (and author(s)) of [PoreNet: CNN-Based Pore Descriptor for High-Resolution Fingerprint Recognition](https://ieeexplore.ieee.org/abstract/document/9063525).
